Jwt authentication
Campbell-Uni/HELPS pull request #10
Opened 2019-04-24 04:26 UTC by diegoportela99

Authentication for users

2019-04-24 10:59 UTC, ghost requested changes
I did some very surface level testing and found a few issues so take this review with a grain of salt. 

I would suggest fixing the endpoints and protecting the user controller before merging (definitely before merging into develop) but you can merge this as is if you would prefer.

2019-04-24 10:59 UTC, ghost commented on HELPS/Controllers/UserController.cs
> +                return BadRequest(new { message = "Username or password is incorrect" });
Wrong response code, should be 401

2019-04-24 10:59 UTC, ghost commented on HELPS/Controllers/UserController.cs
> +            return Ok(user);
Returns invalid object (see spec), Token should be renamed to AccessToken and should include isAdmin

2019-04-24 10:59 UTC, Campbell-Uni commented on HELPS/Startup.cs
> +
Missing UseAuthentication()?

2019-04-24 10:59 UTC, Campbell-Uni commented on HELPS/Controllers/UserController.cs
> +        public IActionResult Authenticate([FromBody]User userParam)
This endpoint does not match spec, should be api/login

2019-04-24 10:59 UTC, Campbell-Uni commented on HELPS/Controllers/UserController.cs
> +        {
I am assuming this is for testing but definitely should not be included in production

2019-05-15 08:48 UTC, diegoportela99 commented on HELPS/Startup.cs
> +                    .AddAuthentication();
Is this all that's needed? i'm not too sure

2019-06-01 02:12 UTC, merged